meta_product_name: "Share"

meta_title: "Share Campus – Seul nous allons vite, ensemble nous allons plus loin"

meta_description: "Share est le premier campus virtuel créé pour les étudiants par des étudiants. Grâce à Share, vous pourrez collaborer, échanger, tisser du lien et ainsi améliorer votre expérience étudiante."

meta_image: "campus.png"
